/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.arrowhead.client.consumer.lpcap;

public class testeJNI {
  public final static native void Queue_capacity_set(long jarg1, Queue jarg1_, int jarg2);
  public final static native int Queue_capacity_get(long jarg1, Queue jarg1_);
  public final static native void Queue_size_set(long jarg1, Queue jarg1_, int jarg2);
  public final static native int Queue_size_get(long jarg1, Queue jarg1_);
  public final static native void Queue_front_set(long jarg1, Queue jarg1_, int jarg2);
  public final static native int Queue_front_get(long jarg1, Queue jarg1_);
  public final static native void Queue_rear_set(long jarg1, Queue jarg1_, int jarg2);
  public final static native int Queue_rear_get(long jarg1, Queue jarg1_);
  public final static native void Queue_elements_set(long jarg1, Queue jarg1_, long jarg2);
  public final static native long Queue_elements_get(long jarg1, Queue jarg1_);
  public final static native long new_Queue();
  public final static native void delete_Queue(long jarg1);
  public final static native void dev_set(String jarg1);
  public final static native String dev_get();
  public final static native void descr_set(long jarg1);
  public final static native long descr_get();
  public final static native void filter_set(String jarg1);
  public final static native String filter_get();
  public final static native long createQueue(int jarg1);
  public final static native void Dequeue(long jarg1, Queue jarg1_);
  public final static native String front(long jarg1, Queue jarg1_);
  public final static native void Enqueue(long jarg1, Queue jarg1_, String jarg2);
  public final static native void handleDev(String jarg1);
  public final static native void handleDescr();
  public final static native void capture(long jarg1, Queue jarg1_);
  public final static native void stop(long jarg1);
  public final static native void capture1(long jarg1, Queue jarg1_);
}
