/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.arrowhead.client.consumer.lpcap;

public class teste {
  public static void setDev(String value) {
    testeJNI.dev_set(value);
  }

  public static String getDev() {
    return testeJNI.dev_get();
  }

  public static void setDescr(SWIGTYPE_p_pcap_t value) {
    testeJNI.descr_set(SWIGTYPE_p_pcap_t.getCPtr(value));
  }

  public static SWIGTYPE_p_pcap_t getDescr() {
    long cPtr = testeJNI.descr_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_pcap_t(cPtr, false);
  }

  public static void setFilter(String value) {
    testeJNI.filter_set(value);
  }

  public static String getFilter() {
    return testeJNI.filter_get();
  }

  public static Queue createQueue(int maxElements) {
    long cPtr = testeJNI.createQueue(maxElements);
    return (cPtr == 0) ? null : new Queue(cPtr, false);
  }

  public static void Dequeue(Queue Q) {
    testeJNI.Dequeue(Queue.getCPtr(Q), Q);
  }

  public static String front(Queue Q) {
    return testeJNI.front(Queue.getCPtr(Q), Q);
  }

  public static void Enqueue(Queue Q, String element) {
    testeJNI.Enqueue(Queue.getCPtr(Q), Q, element);
  }

  public static void handleDev(String netif) {
    testeJNI.handleDev(netif);
  }

  public static void handleDescr() {
    testeJNI.handleDescr();
  }

  public static void capture(Queue q) {
    testeJNI.capture(Queue.getCPtr(q), q);
  }

  public static void stop(SWIGTYPE_p_pcap_t descr) {
    testeJNI.stop(SWIGTYPE_p_pcap_t.getCPtr(descr));
  }

  public static void capture1(Queue q) {
    testeJNI.capture1(Queue.getCPtr(q), q);
  }

}
